<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Launcher</AssemblyName>
    <RootNamespace>Ideo.TopSolidLauncher</RootNamespace>
    <Version>0.3.0</Version>
    <FileVersion>0.3.0.0</FileVersion>
    <AssemblyVersion>0.3.0.0</AssemblyVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\IdeoLauncher.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\IdeoBackground.jpg" />
    <Resource Include="Assets\IdeoLauncher.ico" />
    <Resource Include="Assets\IdeoLogo.png" />
    <Resource Include="Assets\IdeoMark.png" />
  </ItemGroup>
</Project>
